Disable gem liquid-c
I get the following error during bundle:

```
Installing liquid-c 4.0.0 with native extensions
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.

    current directory: .rvm/gems/ruby-3.1.2@torrocus.com--blog/gems/liquid-c-4.0.0/ext/liquid_c
.rvm/rubies/ruby-3.1.2/bin/ruby -I .rvm/rubies/ruby-3.1.2/lib/ruby/3.1.0 -r ./siteconf20221103-27981-ysbr6a.rb extconf.rb
creating Makefile

current directory: .rvm/gems/ruby-3.1.2@torrocus.com--blog/gems/liquid-c-4.0.0/ext/liquid_c
make DESTDIR\= clean

current directory: .rvm/gems/ruby-3.1.2@torrocus.com--blog/gems/liquid-c-4.0.0/ext/liquid_c
make DESTDIR\=
compiling block.c
block.c: In function ‘init_liquid_block’:
block.c:126:6: error: old-style function definition [-Werror=old-style-definition]
  126 | void init_liquid_block()
      |      ^~~~~~~~~~~~~~~~~
block.c: At top level:
cc1: note: unrecognized command-line option ‘-Wno-self-assign’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-parentheses-equality’ may have been intended to silence earlier diagnostics
cc1: note: unrecognized command-line option ‘-Wno-constant-logical-operand’ may have been intended to silence earlier diagnostics
cc1: all warnings being treated as errors
make: *** [Makefile:246: block.o] Error 1

make failed, exit code 2

Gem files will remain installed in .rvm/gems/ruby-3.1.2@torrocus.com--blog/gems/liquid-c-4.0.0 for inspection.
Results logged to .rvm/gems/ruby-3.1.2@torrocus.com--blog/extensions/x86_64-linux/3.1.0/liquid-c-4.0.0/gem_make.out

An error occurred while installing liquid-c (4.0.0), and Bundler cannot continue.
Make sure that `gem install liquid-c -v '4.0.0' --source 'https://rubygems.org/'` succeeds before bundling.

In Gemfile:
  liquid-c
```

I comment on this gem because I don't use it.